
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'enpal_assessment_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'enpal_assessment_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"



# -------------------------------
# Adding varibale mappings heret=wha
# -------------------------------
vars:
  stg_schemas:
    stg_users: pipedrive_analytics
    stg_activity: pipedrive_analytics
    stg_activity_types: pipedrive_analytics
    stg_deal_changes: pipedrive_analytics
    stg_fields: pipedrive_analytics
    stg_stages: pipedrive_analytics
    stg_lost_reasons: pipedrive_analytics

  int_schemas:
    int_deal_changes: pipedrive_analytics
    int_activity: pipedrive_analytics

  rep_schemas:
    rep_sales_funnel_monthly: pipedrive_analytics

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  enpal_assessment_project:
    # Config indicated by + and applies to all files under models/example/
    +schema: pipedrive_analytics
    +materialized: table
